- name: Asegurar que el Namespace existe
  kubernetes.core.k8s:
    name: voting-app
    kind: Namespace
    state: present

- name: Crear el Persistent Volume Claim para Redis
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-pvc
        namespace: voting-app
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: default 
        resources:
          requests:
            storage: 1Gi



- name: Desplegar Backend (Redis) y su Service
  kubernetes.core.k8s:
    state: present
    definition:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: azure-vote-back
          namespace: voting-app
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: azure-vote-back
          template:
            metadata:
              labels:
                app: azure-vote-back
            spec:
              initContainers:
              - name: fix-permissions
                image: busybox
                command: ["sh", "-c", "chown -R 999:999 /data"]
                volumeMounts:
                - name: redis-data
                  mountPath: /data
              containers:
              - name: azure-vote-back
                image: "{{ acr_login_server }}/redis:casopractico2"
                securityContext:
                  runAsUser: 0
                  fsGroup: 999
                args: ["redis-server", "--appendonly", "yes"]
                ports:
                - containerPort: 6379
                volumeMounts:
                - name: redis-data
                  mountPath: /data
              volumes:
              - name: redis-data
                persistentVolumeClaim:
                  claimName: redis-pvc

      - apiVersion: v1
        kind: Service
        metadata:
          name: azure-vote-back
          namespace: voting-app
        spec:
          ports:
          - port: 6379
          selector:
            app: azure-vote-back

- name: Desplegar Frontend y Service Público
  kubernetes.core.k8s:
    state: present
    definition:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: azure-vote-front
          namespace: voting-app
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: azure-vote-front
          template:
            metadata:
              labels:
                app: azure-vote-front
            spec:
              containers:
              - name: azure-vote-front
                image: "{{ acr_login_server }}/azure-vote-front:casopractico2"
                env:
                - name: REDIS
                  value: "azure-vote-back" 
                ports:
                - containerPort: 80

      - apiVersion: v1
        kind: Service
        metadata:
          name: azure-vote-front
          namespace: voting-app
        spec:
          type: LoadBalancer
          ports:
          - port: 80
          selector:
            app: azure-vote-front

